; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s --check-prefix=LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s --check-prefix=LA64

define void @fptoui_v8f32_v8i32(ptr %res, ptr %in){
; LA32-LABEL: fptoui_v8f32_v8i32:
; LA32:       # %bb.0:
; LA32-NEXT:    xvld $xr0, $a1, 0
; LA32-NEXT:    xvftintrz.wu.s $xr0, $xr0
; LA32-NEXT:    xvst $xr0, $a0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: fptoui_v8f32_v8i32:
; LA64:       # %bb.0:
; LA64-NEXT:    xvld $xr0, $a1, 0
; LA64-NEXT:    xvftintrz.wu.s $xr0, $xr0
; LA64-NEXT:    xvst $xr0, $a0, 0
; LA64-NEXT:    ret
  %v0 = load <8 x float>, ptr %in
  %v1 = fptoui <8 x float> %v0 to <8 x i32>
  store <8 x i32> %v1, ptr %res
  ret void
}

define void @fptoui_v4f64_v4i64(ptr %res, ptr %in){
; LA32-LABEL: fptoui_v4f64_v4i64:
; LA32:       # %bb.0:
; LA32-NEXT:    xvld $xr0, $a1, 0
; LA32-NEXT:    xvftintrz.lu.d $xr0, $xr0
; LA32-NEXT:    xvst $xr0, $a0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: fptoui_v4f64_v4i64:
; LA64:       # %bb.0:
; LA64-NEXT:    xvld $xr0, $a1, 0
; LA64-NEXT:    xvftintrz.lu.d $xr0, $xr0
; LA64-NEXT:    xvst $xr0, $a0, 0
; LA64-NEXT:    ret
  %v0 = load <4 x double>, ptr %in
  %v1 = fptoui <4 x double> %v0 to <4 x i64>
  store <4 x i64> %v1, ptr %res
  ret void
}

define void @fptoui_v4f64_v4i32(ptr %res, ptr %in){
; LA32-LABEL: fptoui_v4f64_v4i32:
; LA32:       # %bb.0:
; LA32-NEXT:    xvld $xr0, $a1, 0
; LA32-NEXT:    xvftintrz.lu.d $xr0, $xr0
; LA32-NEXT:    xvpermi.d $xr1, $xr0, 238
; LA32-NEXT:    xvpickev.w $xr0, $xr1, $xr0
; LA32-NEXT:    vst $vr0, $a0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: fptoui_v4f64_v4i32:
; LA64:       # %bb.0:
; LA64-NEXT:    xvld $xr0, $a1, 0
; LA64-NEXT:    xvftintrz.lu.d $xr0, $xr0
; LA64-NEXT:    xvpermi.d $xr1, $xr0, 238
; LA64-NEXT:    xvpickev.w $xr0, $xr1, $xr0
; LA64-NEXT:    vst $vr0, $a0, 0
; LA64-NEXT:    ret
  %v0 = load <4 x double>, ptr %in
  %v1 = fptoui <4 x double> %v0 to <4 x i32>
  store <4 x i32> %v1, ptr %res
  ret void
}

define void @fptoui_v8f64_v8i32(ptr %res, ptr %in){
; LA32-LABEL: fptoui_v8f64_v8i32:
; LA32:       # %bb.0:
; LA32-NEXT:    xvld $xr0, $a1, 32
; LA32-NEXT:    xvld $xr1, $a1, 0
; LA32-NEXT:    xvftintrz.lu.d $xr0, $xr0
; LA32-NEXT:    xvpermi.d $xr2, $xr0, 238
; LA32-NEXT:    xvpickev.w $xr0, $xr2, $xr0
; LA32-NEXT:    xvftintrz.lu.d $xr1, $xr1
; LA32-NEXT:    xvpermi.d $xr2, $xr1, 238
; LA32-NEXT:    xvpickev.w $xr1, $xr2, $xr1
; LA32-NEXT:    xvpermi.q $xr1, $xr0, 2
; LA32-NEXT:    xvst $xr1, $a0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: fptoui_v8f64_v8i32:
; LA64:       # %bb.0:
; LA64-NEXT:    xvld $xr0, $a1, 32
; LA64-NEXT:    xvld $xr1, $a1, 0
; LA64-NEXT:    xvftintrz.lu.d $xr0, $xr0
; LA64-NEXT:    xvpermi.d $xr2, $xr0, 238
; LA64-NEXT:    xvpickev.w $xr0, $xr2, $xr0
; LA64-NEXT:    xvftintrz.lu.d $xr1, $xr1
; LA64-NEXT:    xvpermi.d $xr2, $xr1, 238
; LA64-NEXT:    xvpickev.w $xr1, $xr2, $xr1
; LA64-NEXT:    xvpermi.q $xr1, $xr0, 2
; LA64-NEXT:    xvst $xr1, $a0, 0
; LA64-NEXT:    ret
  %v0 = load <8 x double>, ptr %in
  %v1 = fptoui <8 x double> %v0 to <8 x i32>
  store <8 x i32> %v1, ptr %res
  ret void
}

define void @fptoui_v4f32_v4i64(ptr %res, ptr %in){
; LA32-LABEL: fptoui_v4f32_v4i64:
; LA32:       # %bb.0:
; LA32-NEXT:    vld $vr0, $a1, 0
; LA32-NEXT:    vftintrz.wu.s $vr0, $vr0
; LA32-NEXT:    vext2xv.du.wu $xr0, $xr0
; LA32-NEXT:    xvst $xr0, $a0, 0
; LA32-NEXT:    ret
;
; LA64-LABEL: fptoui_v4f32_v4i64:
; LA64:       # %bb.0:
; LA64-NEXT:    vld $vr0, $a1, 0
; LA64-NEXT:    vftintrz.wu.s $vr0, $vr0
; LA64-NEXT:    vext2xv.du.wu $xr0, $xr0
; LA64-NEXT:    xvst $xr0, $a0, 0
; LA64-NEXT:    ret
  %v0 = load <4 x float>, ptr %in
  %v1 = fptoui <4 x float> %v0 to <4 x i64>
  store <4 x i64> %v1, ptr %res
  ret void
}
