; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=loongarch64-unknown-linux-gnu -passes=pre-isel-intrinsic-lowering -S < %s | FileCheck %s

; LoongArch expands @llvm.can.load.speculatively to an alignment check. A
; naturally aligned access of at most one page cannot cross a page boundary.
; LoongArch has no memory tagging, so sizes above 16 bytes are allowed.

define i1 @can_load_speculatively_8(ptr %ptr) {
; CHECK-LABEL: @can_load_speculatively_8(
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[PTR:%.*]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = and i64 [[TMP1]], 7
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[TMP2]], 0
; CHECK-NEXT:    ret i1 [[TMP3]]
;
  %can_load = call i1 @llvm.can.load.speculatively.p0(ptr %ptr, i64 8)
  ret i1 %can_load
}

define i1 @can_load_speculatively_16(ptr %ptr) {
; CHECK-LABEL: @can_load_speculatively_16(
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[PTR:%.*]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = and i64 [[TMP1]], 15
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[TMP2]], 0
; CHECK-NEXT:    ret i1 [[TMP3]]
;
  %can_load = call i1 @llvm.can.load.speculatively.p0(ptr %ptr, i64 16)
  ret i1 %can_load
}

define i1 @can_load_speculatively_32(ptr %ptr) {
; CHECK-LABEL: @can_load_speculatively_32(
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[PTR:%.*]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = and i64 [[TMP1]], 31
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[TMP2]], 0
; CHECK-NEXT:    ret i1 [[TMP3]]
;
  %can_load = call i1 @llvm.can.load.speculatively.p0(ptr %ptr, i64 32)
  ret i1 %can_load
}

define i1 @can_load_speculatively_64(ptr %ptr) {
; CHECK-LABEL: @can_load_speculatively_64(
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[PTR:%.*]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = and i64 [[TMP1]], 63
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[TMP2]], 0
; CHECK-NEXT:    ret i1 [[TMP3]]
;
  %can_load = call i1 @llvm.can.load.speculatively.p0(ptr %ptr, i64 64)
  ret i1 %can_load
}

; Larger than the minimum page size, so no check is possible.
define i1 @can_load_speculatively_8192(ptr %ptr) {
; CHECK-LABEL: @can_load_speculatively_8192(
; CHECK-NEXT:    ret i1 false
;
  %can_load = call i1 @llvm.can.load.speculatively.p0(ptr %ptr, i64 8192)
  ret i1 %can_load
}

; Non-default address space is rejected.
define i1 @can_load_speculatively_as1(ptr addrspace(1) %ptr) {
; CHECK-LABEL: @can_load_speculatively_as1(
; CHECK-NEXT:    ret i1 false
;
  %can_load = call i1 @llvm.can.load.speculatively.p1(ptr addrspace(1) %ptr, i64 16)
  ret i1 %can_load
}

declare i1 @llvm.can.load.speculatively.p0(ptr, i64)
declare i1 @llvm.can.load.speculatively.p1(ptr addrspace(1), i64)
