; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch64 --mattr=+lsx --verify-machineinstrs < %s | FileCheck %s

declare i64 @llvm.experimental.cttz.elts.i64.v2i1(<2 x i1>, i1)
declare i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1>, i1)

define i64 @first_set_lane_v2i64(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: first_set_lane_v2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vseq.d $vr0, $vr0, $vr1
; CHECK-NEXT:    vmskltz.d $vr0, $vr0
; CHECK-NEXT:    vpickve2gr.hu $a0, $vr0, 0
; CHECK-NEXT:    ori $a0, $a0, 4
; CHECK-NEXT:    ctz.d $a0, $a0
; CHECK-NEXT:    ret
  %cmp = icmp eq <2 x i64> %a, %b
  %r = call i64 @llvm.experimental.cttz.elts.i64.v2i1(<2 x i1> %cmp, i1 false)
  ret i64 %r
}

define i64 @first_set_lane_v2i64_poison(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: first_set_lane_v2i64_poison:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vseq.d $vr0, $vr0, $vr1
; CHECK-NEXT:    vmskltz.d $vr0, $vr0
; CHECK-NEXT:    vpickve2gr.hu $a0, $vr0, 0
; CHECK-NEXT:    ctz.d $a0, $a0
; CHECK-NEXT:    ret
  %cmp = icmp eq <2 x i64> %a, %b
  %r = call i64 @llvm.experimental.cttz.elts.i64.v2i1(<2 x i1> %cmp, i1 true)
  ret i64 %r
}

define i64 @first_set_lane_v4i32(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: first_set_lane_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vseq.w $vr0, $vr0, $vr1
; CHECK-NEXT:    vmskltz.w $vr0, $vr0
; CHECK-NEXT:    vpickve2gr.hu $a0, $vr0, 0
; CHECK-NEXT:    ori $a0, $a0, 16
; CHECK-NEXT:    ctz.d $a0, $a0
; CHECK-NEXT:    ret
  %cmp = icmp eq <4 x i32> %a, %b
  %r = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> %cmp, i1 false)
  ret i64 %r
}
