; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch64 --mattr=+lsx --verify-machineinstrs < %s | FileCheck %s

declare void @sink()

;; A lane mask that is only tested against zero should use the whole-vector
;; test, which writes a condition flag directly, instead of materializing the
;; mask in a GPR.

define i1 @any_lane_set(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: any_lane_set:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vseq.d $vr0, $vr0, $vr1
; CHECK-NEXT:    vsetnez.v $fcc0, $vr0
; CHECK-NEXT:    movcf2gr $a0, $fcc0
; CHECK-NEXT:    ret
  %cmp = icmp eq <2 x i64> %a, %b
  %bc = bitcast <2 x i1> %cmp to i2
  %any = icmp ne i2 %bc, 0
  ret i1 %any
}

define i1 @no_lane_set(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: no_lane_set:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vseq.w $vr0, $vr0, $vr1
; CHECK-NEXT:    vseteqz.v $fcc0, $vr0
; CHECK-NEXT:    movcf2gr $a0, $fcc0
; CHECK-NEXT:    ret
  %cmp = icmp eq <4 x i32> %a, %b
  %bc = bitcast <4 x i1> %cmp to i4
  %none = icmp eq i4 %bc, 0
  ret i1 %none
}

;; A branch should consume the flag with bcnez/bceqz, with no GPR transfer.

define void @branch_any_lane_set(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: branch_any_lane_set:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vseq.d $vr0, $vr0, $vr1
; CHECK-NEXT:    vseteqz.v $fcc0, $vr0
; CHECK-NEXT:    bcnez $fcc0, .LBB2_2
; CHECK-NEXT:  # %bb.1: # %hit
; CHECK-NEXT:    addi.d $sp, $sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    st.d $ra, $sp, 8 # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 1, -8
; CHECK-NEXT:    pcaddu18i $ra, %call36(sink)
; CHECK-NEXT:    jirl $ra, $ra, 0
; CHECK-NEXT:    ld.d $ra, $sp, 8 # 8-byte Folded Reload
; CHECK-NEXT:    addi.d $sp, $sp, 16
; CHECK-NEXT:  .LBB2_2: # %exit
; CHECK-NEXT:    ret
  %cmp = icmp eq <2 x i64> %a, %b
  %bc = bitcast <2 x i1> %cmp to i2
  %any = icmp ne i2 %bc, 0
  br i1 %any, label %hit, label %exit
hit:
  call void @sink()
  br label %exit
exit:
  ret void
}

;; Negative test: x < 0 lowers to vmskltz.d applied to the raw vector rather
;; than to a mask, so the fold must not fire. For <1, 0> the mask is zero while
;; the vector is nonzero.

define i1 @any_lane_negative(<2 x i64> %v) {
; CHECK-LABEL: any_lane_negative:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmskltz.d $vr0, $vr0
; CHECK-NEXT:    vpickve2gr.hu $a0, $vr0, 0
; CHECK-NEXT:    sltu $a0, $zero, $a0
; CHECK-NEXT:    ret
  %cmp = icmp slt <2 x i64> %v, zeroinitializer
  %bc = bitcast <2 x i1> %cmp to i2
  %any = icmp ne i2 %bc, 0
  ret i1 %any
}
