; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch64 --mattr=+lasx --verify-machineinstrs < %s | FileCheck %s

declare i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1>, i1)
declare i64 @llvm.experimental.cttz.elts.i64.v8i1(<8 x i1>, i1)

;; The index of the first set lane comes from counting trailing zeros of the
;; lane bitmask, not from the generic step-vector/AND/UMAX expansion.

;; zero_is_poison is clear, so a mask of zero has to produce the vector length.
;; Setting bit VL before the count arranges that.
define i64 @first_set_lane_v4i64(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: first_set_lane_v4i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvseq.d $xr0, $xr0, $xr1
; CHECK-NEXT:    xvmskltz.d $xr0, $xr0
; CHECK-NEXT:    xvpickve2gr.wu $a0, $xr0, 0
; CHECK-NEXT:    xvpickve2gr.wu $a1, $xr0, 4
; CHECK-NEXT:    bstrins.d $a0, $a1, 3, 2
; CHECK-NEXT:    ori $a0, $a0, 16
; CHECK-NEXT:    ctz.d $a0, $a0
; CHECK-NEXT:    ret
  %cmp = icmp eq <4 x i64> %a, %b
  %r = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> %cmp, i1 false)
  ret i64 %r
}

;; zero_is_poison is set, so no fixup is needed.
define i64 @first_set_lane_v4i64_poison(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: first_set_lane_v4i64_poison:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvseq.d $xr0, $xr0, $xr1
; CHECK-NEXT:    xvmskltz.d $xr0, $xr0
; CHECK-NEXT:    xvpickve2gr.wu $a0, $xr0, 0
; CHECK-NEXT:    xvpickve2gr.wu $a1, $xr0, 4
; CHECK-NEXT:    bstrins.d $a0, $a1, 3, 2
; CHECK-NEXT:    ctz.d $a0, $a0
; CHECK-NEXT:    ret
  %cmp = icmp eq <4 x i64> %a, %b
  %r = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> %cmp, i1 true)
  ret i64 %r
}

define i64 @first_set_lane_v8i32(<8 x i32> %a, <8 x i32> %b) {
; CHECK-LABEL: first_set_lane_v8i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvseq.w $xr0, $xr0, $xr1
; CHECK-NEXT:    xvmskltz.w $xr0, $xr0
; CHECK-NEXT:    xvpickve2gr.wu $a0, $xr0, 0
; CHECK-NEXT:    xvpickve2gr.wu $a1, $xr0, 4
; CHECK-NEXT:    bstrins.d $a0, $a1, 7, 4
; CHECK-NEXT:    ori $a0, $a0, 256
; CHECK-NEXT:    ctz.d $a0, $a0
; CHECK-NEXT:    ret
  %cmp = icmp eq <8 x i32> %a, %b
  %r = call i64 @llvm.experimental.cttz.elts.i64.v8i1(<8 x i1> %cmp, i1 false)
  ret i64 %r
}
