; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch64 --mattr=+lasx --verify-machineinstrs < %s | FileCheck %s

declare void @sink()

;; A lane mask that is only tested against zero should use the whole-vector
;; test. On LASX this also avoids the second half-extract and the merge of the
;; two mask halves.

define i1 @any_lane_set(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: any_lane_set:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvseq.d $xr0, $xr0, $xr1
; CHECK-NEXT:    xvsetnez.v $fcc0, $xr0
; CHECK-NEXT:    movcf2gr $a0, $fcc0
; CHECK-NEXT:    ret
  %cmp = icmp eq <4 x i64> %a, %b
  %bc = bitcast <4 x i1> %cmp to i4
  %any = icmp ne i4 %bc, 0
  ret i1 %any
}

define i1 @no_lane_set(<8 x i32> %a, <8 x i32> %b) {
; CHECK-LABEL: no_lane_set:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvseq.w $xr0, $xr0, $xr1
; CHECK-NEXT:    xvseteqz.v $fcc0, $xr0
; CHECK-NEXT:    movcf2gr $a0, $fcc0
; CHECK-NEXT:    ret
  %cmp = icmp eq <8 x i32> %a, %b
  %bc = bitcast <8 x i1> %cmp to i8
  %none = icmp eq i8 %bc, 0
  ret i1 %none
}

define void @branch_any_lane_set(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: branch_any_lane_set:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvseq.d $xr0, $xr0, $xr1
; CHECK-NEXT:    xvseteqz.v $fcc0, $xr0
; CHECK-NEXT:    bcnez $fcc0, .LBB2_2
; CHECK-NEXT:  # %bb.1: # %hit
; CHECK-NEXT:    addi.d $sp, $sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    st.d $ra, $sp, 8 # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 1, -8
; CHECK-NEXT:    pcaddu18i $ra, %call36(sink)
; CHECK-NEXT:    jirl $ra, $ra, 0
; CHECK-NEXT:    ld.d $ra, $sp, 8 # 8-byte Folded Reload
; CHECK-NEXT:    addi.d $sp, $sp, 16
; CHECK-NEXT:  .LBB2_2: # %exit
; CHECK-NEXT:    ret
  %cmp = icmp eq <4 x i64> %a, %b
  %bc = bitcast <4 x i1> %cmp to i4
  %any = icmp ne i4 %bc, 0
  br i1 %any, label %hit, label %exit
hit:
  call void @sink()
  br label %exit
exit:
  ret void
}

;; Negative test: the fold must not fire when the source is the raw vector
;; rather than a mask.

define i1 @any_lane_negative(<4 x i64> %v) {
; CHECK-LABEL: any_lane_negative:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvmskltz.d $xr0, $xr0
; CHECK-NEXT:    xvpickve2gr.wu $a0, $xr0, 0
; CHECK-NEXT:    xvpickve2gr.wu $a1, $xr0, 4
; CHECK-NEXT:    bstrins.d $a0, $a1, 3, 2
; CHECK-NEXT:    sltu $a0, $zero, $a0
; CHECK-NEXT:    ret
  %cmp = icmp slt <4 x i64> %v, zeroinitializer
  %bc = bitcast <4 x i1> %cmp to i4
  %any = icmp ne i4 %bc, 0
  ret i1 %any
}
